openapi: '3.0.2'
info:
  title: API Articoding
  description: This API is used to handle requests to the backend of the Articoding video game.
  version: '1.0.0'
servers:
  - url: http://localhost:3001
    description: 'Entorno de desarrollo de apis'
tags:
  - name: level
    description: Everything about a level
paths:
  /api/level/categories:
    get:
      tags:
      - level
      summary: Get all the categories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryArray' 
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/level/{id}:
    get:
      tags:
      - level
      summary: Get an specific level
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The level ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Level' 
        '500':
          $ref: '#/components/responses/InternalServerError'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/level/create:
    post:
      tags:
      - level
      summary: Insert a level in the DataBase
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Level'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Level' 
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    InternalServerError:
      description: Internal Server Error
    NotFound:
      description: Can't be found
  schemas:
    Level:
      type: object
      required: 
       - user
       - category
       - self
       - title
       - data 
      properties:
        id:
          type: integer
          format: uuid
          readOnly: true
        user:
          type: integer
        category:
          type: integer
        self:
          type: integer
        title:
          type: string
        data:
          type: string
    Category:
      type: object
      properties: 
        id:
          type: integer
          format: uuid
          readOnly: true
        name:
          type: string
        description:
          type: string
    CategoryArray:
      type: array
      items:
        $ref: '#/components/schemas/Category'
        
        
        