openapi: '3.0.2'
info:
  title: API Articoding
  description: This API is used to handle requests to the backend of the Articoding video game.
  version: '1.0.0'
servers:
  - url: http://localhost:3001
tags:
  - name: level
    description: Everything about a level
paths:
  /api/level/categories:
    get:
      tags:
      - level
      summary: Get all the categories
      responses:
        '200':
          description: OK
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/level/create:
    post:
      tags:
      - level
      summary: Insert a level in the DataBase
      responses:
        '200':
          description: OK
components:
  responses:
    InternalServerError:
      description: Internal Server Error